"""add role column to users

Revision ID: 3b4ebdfe987c
Revises: 
Create Date: 2025-05-13 16:22:34.310581
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4ebdfe987c'
down_revision: Union[str, None] = None  # This is correct if it's the first migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the 'role' column with a default value of 'user' for existing rows
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'hashed_password', existing_type=sa.VARCHAR(), nullable=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
